server {
    listen 80;
    server_name localhost;

    # Directorio donde están los archivos de Angular
    root /usr/share/nginx/html;
    index index.html;

    # Fallback para el enrutamiento de Angular (SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Caché para archivos estáticos
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}
